version: '3'
services:
  editor:
    build: editor/
    restart: always
    links: ["storage"]
    ports:
      - "8080:8080"
  core:
    build: core/
    restart: always
    volumes:
      - ./core:/core
    command: ["sleep", "infinity"]
  storage:
    build: storage/
    restart: always
    environment:
      POSTGRES_PASSWORD: jarsonmud
    ports:
      - "5433:5432"
  aberbrowser:
    build: aberbrowser/
    volumes:
      - ./aberbrowser:/aberbrowser
    restart: always
    ports:
      - "9094:8080"
  aberbrowser-app:
    build: aberbrowser/app
    volumes:
      - ./aberbrowser:/aberbrowser
    restart: always
    ports:
      - "9095:5000"
