version: '3'
services:
  editor:
    build: editor/
    restart: always
    ports:
      - "8080:8080"
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: twitch
    ports:
      - "5432:5432"
